version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "parcel"
        versions: ["^2.0.0-nightly.0"]
      - dependency-name: "@parcel/*"
        versions: ["^2.0.0-nightly.0"]

  # Maintain dependencies for Elm
  - package-ecosystem: "elm"
    directory: "/"
    schedule:
      interval: "daily"
