[build]
    publish = "dist/"
    command = "yarn run build"

[build.environment]
    ELM_HOME = "$NETLIFY_BUILD_BASE/cache/elm"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
